services:

  db:
    image: postgres:16
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: video_games
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: my_spring_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/video_games
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8080"

  frontend:
    image: leon38asim/frontendcompose
    container_name: my_frontend
    depends_on:
      - backend
    ports:
      - "8081:80"
#    volumes:
#      - ./frontend:/usr/share/nginx/html

volumes:
  postgres-data:
